[project]
name = "chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyarrow>=22.0.0",
    "regex>=2025.11.3",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]
